server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机
      defaultZone: http://eureka-server7001.com:7001/eureka/
      #集群
      #defaultZone: @config.server-addr@
  instance:
    instance-id: consumerOrder80
    prefer-ip-address: true
