server:
  port: 3344

spring:
  application:
    name: cloud-configer-center
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zwssunny/springCloudConfig
          search-paths: test


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机
      defaultZone: http://eureka-server7001.com:7001/eureka/
      #集群
      #defaultZone: @config.server-addr@
  instance:
    instance-id: configercenter3344
    prefer-ip-address: true

