server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator: #开启从注册中心动态识别路由的功能
          enabled: true
      routes:
        - id: payment_routh
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**
            - After=2022-10-16T16:30:00.000+08:00[Asia/Shanghai]

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
            - After=2022-10-16T16:30:00.000+08:00[Asia/Shanghai]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机
      defaultZone: http://eureka-server7001.com:7001/eureka/
      #集群
      #defaultZone: @config.server-addr@
  instance:
    instance-id: cloudgateway9527
    prefer-ip-address: true
    # #心跳间隔时间
    # lease-renewal-interval-in-seconds: 1
    # #服务器在收到最后一次心跳后等待时间，超时删除服务
    # lease-expiration-duration-in-seconds: 5
