server:
  port: 9001

spring:
  application:
    name: cloudalibaba-payment-service
  cloud:
    nacos:
      server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource: #规则存储参数
        ds1:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow


# mangement:
#   endpoints:
#     web:
#       exposure:
#         include: '*'
