server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-order

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      #单机
      defaultZone: http://eureka-server7001.com:7001/eureka/
      #集群
      #defaultZone: @config.server-addr@
  instance:
    instance-id: consumerFeignOrder80
    prefer-ip-address: true

# ribbon: 不对
#   ReadTimeout: 5000
#   ConnectTimeout: 5000
# logging:
#   level:
#     #feign日志级别监控哪个接口
#     com.foresight.springcloud.service.PaymentFeignService: debug
